export const MAX_MANAGED_TIMEOUT_MS: number;
export const EXECUTION_RETENTION_MS: number;
export const MAX_RETAINED_EXECUTIONS: number;
export const MAX_EXECUTION_EVENTS: number;
export const MAX_EXECUTION_STREAMS: number;
export const EXECUTION_STREAM_MS: number;
export const MAX_STDIN_CHUNK_BYTES: number;
export const MAX_STDIN_BYTES: number;
export const MAX_PENDING_STDIN_BYTES: number;
export const EXECUTION_SIGNALS: string[];
export function validTerminalSize(value: unknown): boolean;
export function executionFingerprintValues(body: { command?: string; argv?: string[]; timeoutMs?: number; stdin?: boolean; cwd?: string; env?: Record<string, string>; pty?: {cols: number; rows: number} }): unknown[];
export function validExecutionId(value: unknown): value is string;
export function validExecution(value: unknown): boolean;
export function terminalExecution(record: { status: string }): boolean;
